/**:
  ros__parameters:
    heading_weight: 0.1
    lane_planner:
      trajectory_resolution: 0.5
      include_start_point: true
    gaussian_smoother:
      standard_deviation: 5.0
      kernel_size: 3
